# Generated by Django 4.2.5 on 2023-09-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveTemphere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_id', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('place', models.CharField(blank=True, max_length=250, null=True)),
                ('buka', models.CharField(blank=True, max_length=250, null=True)),
                ('muka', models.CharField(blank=True, max_length=250, null=True)),
                ('maka', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('place', models.CharField(blank=True, max_length=250, null=True)),
                ('buka', models.CharField(blank=True, max_length=250, null=True)),
                ('muka', models.CharField(blank=True, max_length=250, null=True)),
                ('maka', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
