# Generated by Django 4.2.5 on 2023-09-28 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_movetemphere_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movetemphere',
            name='temp_id',
        ),
    ]
